### ISSUE TITLE
Binary targeting not working

### ISSUE THREAD

**Issue by NathanMcCoy** [dbakewel/netbots#104]
I am trying to implement the binary search aiming for my robot, but I am having issues choosing the correct place to look after each scan. 
For instance, this is what it might try to scan:
![robot is bad](https://user-images.githubusercontent.com/44909830/83909387-8d049780-a71d-11ea-98a9-1561ce78b45a.png)
the direction of the scan is determined by a variable named side, -1 <= side <= 1

def binaryTargeting(presision, start, side):
    
    scanSliceWidth = (math.pi * 2 / presision)
    scanRadEnd = min(start + (scanSliceWidth * side), math.pi * 2)
    log("pres " + str(presision) + " start " + str(start) + " other " + str(scanRadEnd) + " side " + str(side))
    if side > 0:
        scanReply = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': start, 'endRadians': scanRadEnd})
    else:
        scanReply = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': scanRadEnd, 'endRadians': start})
    if scanReply['distance'] != 0:
        if presision == 32:
            return scanReply
        start = scanSliceWidth
        side = -1
        presision = presision * 2
        return binaryTargeting(presision, scanRadEnd, side)
    else:
        if presision == 32:
            scanRadEnd = min((start + scanSliceWidth) * -1, math.pi * 2)
            scanReply = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': scanRadEnd, 'endRadians': start})
            return scanReply
        side = 1
    
    presision = presision * 2
    return binaryTargeting(presision, scanRadEnd, side)

**Comment by dbakewel** [comment]
Hi Nathan,

I think you are a bit off on this and I don't see one easy fix. I'll try and point out several things that i think may be issues. Have a look and revisit your code then repost to this thread and let me know if you are able to work it out.

1. It appears 'side' can be negative so in the code that sets scanRandEnd:
```
scanRadEnd = min(start + (scanSliceWidth * side), math.pi * 2)
```
it is possible to have scanRandEnd be negative. Note that you cannot send a negative angle in a scanRequest message. You may also want to make use of normalizeAngles as described in: https://youtu.be/ZHQQp9Y7gLA 

2. Again, not sure what you mean but looking at your code:
```
if side > 0:
    scanReply = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': start, 'endRadians': scanRadEnd})
else:
    scanReply = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': scanRadEnd, 'endRadians': start})
```
it appears that you may expect one of these scans to go clockwise from start to end. Note that scan is always counter-clockwise from start to end. See docs: https://github.com/dbakewel/netbots#scan 

3. Beyond that I'm not sure you have the correct concept since it is hard to see where you are comparing two scans to choose a direction to keep scanning. I would suggest you write what you have as pseudocode first and run it by hand in you head. Then fill in the code once you know it will work. The pseudocode will be something like this, assuming an iterative solution:
```
start = 0
width = pi * 2
distance = 0
while width > (pi * 2 / 32)
    width = width / 2
    scan1 = scan from start to start + width
    scan2 = scan from start+width to start+width*2
    if scan1 and scan2 both did not find a robot:
        distance = 0
        break out of loop
    if scan2 == 0 or (scan1 distance is closer than scan2 distance):
        start stays the same.
        distance = scan1 distance
    else
         start = start + width
         distance = scan2 distance

if distance != 0
   shoot at start and distance
```
