### ISSUE TITLE
What are the best resources to learn about async programming to apply to the bots?

### ISSUE THREAD

**Issue by MatthewHightech** [dbakewel/netbots#113]
Hello there, 

Mrs. Wear told me that you attempted to teach async bots last year, and it went over most people's heads (understandably) I've been doing some reasearch and attempting to integrate it into my program but don't think it's working...(it's not crashing, it's just running the async functions like regular functions) What resources would you suggust to help me move forward with this? 

Thanks!

**Comment by dbakewel** [comment]
Good question. There is no simple resource for this. I assume you mean you have mostly stopped using netbots_ipc.sendRecvMessage() and are using netbots_ipc.sendMessage() and netbots_ipc.recvMessage() instead. You need to carefully understand how these function work since they return immediately and in the case of sendMessage() you do not know if the message got to the server.

I think the first step is to understand, and I really mean deeply understand, the sendRecvMessage() code in [netbots_ipc](https://github.com/dbakewel/netbots/blob/master/src/netbots_ipc.py). sendRecvMessage() uses sendMessage() and recvMessage() to do it's work. Once you understand sendRecvMessage(), you can create your own version that does more than send one message per step. The server will reply to up to 4 messages from your robot per step. Any small step you can take in this direction would give your robot a huge advantage. There is lots more that can be done to manage messages asynchronously but just work on that first.

Hope that helps. Let me know how it goes.

**Comment by MatthewHightech** [comment]
Neat! Thanks for the tips. The first question I have is - Aren't there certain messages that don't need to be received? In the demo robots code, all the movment and firing are sendrecv messages, but those functions aren't returning any data are they? Or at least none I'm currently using. 

So the only requests it would make sense to use async functions for would be ones that are returning data like scan or get location?

**Comment by dbakewel** [comment]
Well in one way all messages are returning data. For example, if you send a setSpeedRequest and never see a setSpeedReply come back then you don't know if the message made it to the server or was dropped by the network. Just knowing that is useful data. 

Also, scanning is what you want to use async messaging for the most since good robots send most scan messages. One way to do this is to have an array of messages you've sent and expect replies for. Then you can have an array of replies that you received and match them up. Look at how [sendRecvMessage()](https://github.com/dbakewel/netbots/blob/master/src/netbots_ipc.py) uses [msgId](https://github.com/dbakewel/netbots#messages) to match a reply with a sent message. Then you coder could do the following:
1. send several messages (at most 4 per step)
2. collect responses as they arrive and match them to the sent messages.
3. resend messages if no responses showed up in a certain amount of time.
4. once you have enough replies then do something with the collected messages.

That is the basic approach level8 uses.

**Comment by dbakewel** [comment]
Another option is to use [replyData](https://github.com/dbakewel/netbots#messages) which allows attaching more information to a message than msgID. However you need to be careful that your messages are not too big. With replyData you can do more advanced things but be careful how complex you make it. For example, you can make it so a scanReply has a replyData with the same information from the scanRequest that was sent. Then you don't need to match up the scanReply with the scanRequest to know what angles the scanReply refers to since you can store them in the scanRequest replyData and read them from the scanReply replyData.

**Comment by MatthewHightech** [comment]
I see...I might have to read through that a few times, but thanks for the help :) I likley won't be able to get anything like this to work for the course, esspecially since I have a lot of other school work this weekend, but this is an amazing learning tool you've built and I'm very grateful for this resource :) I will definitelycontinue to dabble with these bots over the summer, and maybe even into next year. Thanks for all your hard work!

**Comment by dbakewel** [comment]
Of course, no problem. This is a hard topic so play with it if you have time but make sure you are having fun otherwise their's no point. :)
