### ISSUE TITLE
Robot Scan Inclusive or Exclusive

### ISSUE THREAD

**Issue by raineyfu** [dbakewel/netbots#115]
Suppose there was an enemy robot located at angle 1 radians away from the scanning robot. Would both (scanRequest, 0, 1) and (scanRequest, 1, 2) return the same output?

Are the parameters in scan inclusive or exclusive?

**Comment by dbakewel** [comment]
The server makes use of [netbots_math](https://github.com/dbakewel/netbots/blob/master/src/netbots_math.py).contains() when scanning. In the example you have given it could return the same output. However in any practical sense this is almost impossible since we are using floating point numbers. I would not worry about this when making a robots.

Good question.
