### ISSUE TITLE
Stopping my robot from hitting the walls

### ISSUE THREAD

**Issue by royale-glitch** [dbakewel/netbots#116]
I can't seem to be able to prevent my robot from hitting the walls. I made it such that if its location is < 300 away from the edge, it should pick a random direction in the other way. But it still hits the walls. I also tried making its speed 0 before turning it, but it won't stop

**Comment by dbakewel** [comment]
Without seeing the code I can only guess but here are a few things to consider and ideas to debug the issue. 

I'll assume that you have checked the log output from your robot and you don't see errors and that you have already checked that the code to stop and turn are actually being run. If not, then look at the log output and add some lines to log info about if your code sections are running. Remove the extra logging once you get things working because to much logging will slow down your robot.

Beyond that I would make sure you've read the docs on [Changing Speed and Direction](https://github.com/dbakewel/netbots#changing-direction-and-speed). The key point is that a robot turns very slowly when it's moving fast. Also, a robot takes time to slow down. If you ask for speed of 0 it takes awhile to slow down. If you are going full speed and quickly set speed 0, then turn, then set speed to 100 it will not work since the the robot did not slow down enough before starting the turn. You have set speed 0, wait, then turn, wait, then set speed to 100.

If you have already looked at all that then I suggest you break it down into parts. Start by making a robot that never turns while moving. Just make a robot that stops when it gets close to a wall. After that works then tell it stop WAIT until [you know it has speed of 0](https://github.com/dbakewel/netbots#getspeed) and then turn and then speed up. If that all works then you have your robot turn when it's moving slower but not at 0. Something like that should work well.

Finally, there is an old demo robot called [train.py](https://github.com/dbakewel/netbots/blob/f98ac692d45273c093e4e679c1189c178358aa37/robots/train.py) that may give you some ideas. It's from an old version of netbots so it may not work but it's basic code is good. Train.py just drives around a track going up one wall, along the top, down the other wall, and along the bottom. So it does a lot of what you need to do. However it only goes at 50 speed all the time to make turning easy. It's worth a look but it may be a waste of time.

Good luck and don't forget to star netbots on github!
