### ISSUE TITLE
Netbots Math normalizeAngle() normalizes angles of 2pi

### ISSUE THREAD

**Issue by mcstoer** [dbakewel/netbots#36]
**Describe the bug**
Angles of 2pi are normalized to 0 by netbots math but 2pi is required for scans ending at 2pi.

**To Reproduce**
Use the normalize angle function on 2pi.

**Expected behavior**
Since the server accepts angles of 2pi, the normalize angle function should not normalize angles of 2pi.

**Console Output**
Include error and several lines leading up to the error. Consider including verbose or debug output.
0.0

**Work Around**
Is there a way to work around the problem?
Don't use the normalize angle function on angles of 2pi.

**Comment by dbakewel** [comment]
OK, I see what you are saying. netbots_mat.normalizeAngle() says in the docs that it returns an angle: 0 <= angle <= 2pi, however it really only returns an angle: 0 <= angle < 2pi. Since 0 and 2pi are the same angle we need to ask a few questions:

1. Does it matter that netbots_mat.normalizeAngle() changes 2pi to be 0, since they are the same angle? Perhaps this is fine and we just need to update the docs to match the code.

2. In your example, you assume (without a test case) that scanning is impacted by this. For example, you assume that the following message is not valid, or at least it will not scan a range of 0.5pi:

```
{ 'type': 'scanRequest', 'startRadians': 4.7,  'endRadians': 0 }
```

If you look in the netbots_srvmsghl.scanRequest() function you will see that all the math work is done by netbots_math.contains() function. So the question is, will the message above work in netbots_math.contains()? What about other scans over 0 radians, such as:

```
{ 'type': 'scanRequest', 'startRadians': 4.7,  'endRadians': 1.0 }
```

Look at those functions and see if you can post a specific test case (code snippet) that shows the problem.

**Comment by mcstoer** [comment]
This is important in the scenario where you are scanning from 0 to 2pi.  If 2pi is normalized you scan from 0.0 to 0.0 and get a scan that doesn't scan anything.  The netbots IPC accepts angles of 2pi.

**Comment by dbakewel** [comment]
OK, now we are getting somewhere. My view on this is:

1. 0 and 2pi are exactly the same thing so this not a netbots_math.normalizeAngle() problem.

2. netbots_ipc could be changed to only accept < 2pi rather than <= 2pi. However I don't want to change something that might break existing robots.

3. I think the real problem is that netbots_math.contains() should support from 0 radians to 0 radians. The [docs](https://github.com/dbakewel/netbots#containsx1-y1-startrad-endrad-x2-y2) say that startRad and endRad are interpreted as a **range**, therefore 0 to 0 would be a full circle. Again, 0 and 2pi are the same thing so 0 to 2pi is the same as 0 to 0. The fix would be to change line 53 of netbots_math from
```
if(startRad > endRad)
```
     to
```
if(startRad >= endRad)
```

What do you think?

**Comment by mcstoer** [comment]
I think that solution better fixes the problem than changing netbots_math.normalizeAngle().

**Comment by dbakewel** [comment]
OK, @mcstoer feel free to put in a pull request for it.

**Comment by mcstoer** [comment]
Created a pull request. #38
