### ISSUE TITLE
Location Requests Return the Type of Zone the Robot is in

### ISSUE THREAD

**Issue by jtaevans** [dbakewel/netbots#37]
**Is your feature request related to a problem? Please describe.**
There is currently no way for a robot to know what type of zone it is in.

**Describe the solution you'd like**
Location requests should return a key that contains a string describing the type of zone the robot is in, such as "normal" or "jam" or "lava". 

**Describe alternatives you've considered**
This request could be its own type of request, such as a 'getZoneRequest', as opposed to being a part of the `sendRecvMessage({'type': 'getLocationRequest'})` request.

**Comment by dbakewel** [comment]
There is one enhancement that is needed here. It is not documented that: Jam Zone Radius = Robot Radius * 2. The robot radius is also in the server conf so you can determine the radius of the jam zones. This should be added to the README.md.

**Comment by dbakewel** [comment]
There is one enhancement needed here. The README.md does not state that: **Jam Zone Radius = Robot Radius * 2**. Robot radius is provided in server conf so jam zone radius can be calculated by the robots.

**Comment by dbakewel** [comment]
There is one thing needed here. [README.md](https://github.com/dbakewel/netbots/blob/master/README.md#obstacles-and-jam-zones) should state that this informatoin is in the server conf. Also, it should say that **Jam Zone Radius = Robot Radius * 2**. Since robot radius is also in server conf, jam zone radius an be computed by robot if needed.

**Comment by dbakewel** [comment]
There is one thing needed here. [README.md](https://github.com/dbakewel/netbots/blob/master/README.md#obstacles-and-jam-zones) should state that this informatoin is in the server conf. Also, it should say that **Jam Zone Radius = Robot Radius * 2**. Since robot radius is also in server conf, jam zone radius an be computed by robot if needed.

**Comment by dbakewel** [comment]
There is one thing needed here. [README.md](https://github.com/dbakewel/netbots/blob/master/README.md#obstacles-and-jam-zones) should state that this informatoin is in the server conf. Also, it should say that **Jam Zone Radius = Robot Radius * 2**. Since robot radius is also in server conf, jam zone radius an be computed by robot if needed.

**Comment by dbakewel** [comment]
There is one thing needed here. [README.md](https://github.com/dbakewel/netbots/blob/master/README.md#obstacles-and-jam-zones) should state that this informatoin is in the server conf. Also, it should say that **Jam Zone Radius = Robot Radius * 2**. Since robot radius is also in server conf, jam zone radius an be computed by robot if needed.

**Comment by jtaevans** [comment]
Thanks, I missed that.

**Comment by dbakewel** [comment]
This information is all available in the joinReply conf field. See the following:

https://github.com/dbakewel/netbots/blob/master/README.md#join

https://github.com/dbakewel/netbots/blob/master/README.md#server-configuration

In the server conf see 'obstacles' and 'jamZones'. The same would be true if we add lava zones etc...

Please confirm if that is all you need.
