### ISSUE TITLE
Crediting Authors under GPLv3

### ISSUE THREAD

**Issue by mcstoer** [dbakewel/netbots#69]
GPLv3 requires crediting authors through license notices.

> Why should I put a license notice in each source file? (#NoticeInSourceFile)
You should put a notice at the start of each source file, stating what license it carries, in order to avoid risk of the code's getting disconnected from its license. If your repository's README says that source file is under the GNU GPL, what happens if someone copies that file to another program? That other context may not show what the file's license is. It may appear to have some other license, or no license at all (which would make the code nonfree).
Adding a copyright notice and a license notice at the start of each source file is easy and makes such confusion unlikely.

Using a template as such,
```
<one line to give the program's name and a brief idea of what it does.>
Copyright (C) <yyyy> <author>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

How should we go about doing this?

**Comment by dbakewel** [comment]
That's not technically true. GPLv3 has no requirements for crediting authors. NetBots is crediting authors through the git record. GIt is not perfect but it is much better than most other ways to credit authors. 

Regarding copyright notices, we could do that. Again, it is not required and many projects do not do it. Most of netbots files are useless out of the context of the netbots project. It may be a bit less confusing but at the cost of having garbage at the top of each file. It does not actually add any more protections.

I'll leave this open for now but I don't think we need to do this.

**Comment by dbakewel** [comment]
Sorry, I should have pointed out that you need consider this in the context of all the files in netbots. For example, the image files cannot have this notice applied to them but they are still covered under the GPLv3 notice in the root netbots directory. Adding this to the bat files would reduce their readability since most of the file would be the license notice. That does not help anyone.

**Comment by mcstoer** [comment]
GPLv3 might not credit authors through license notices, but they do require attribution.
See https://opensource.stackexchange.com/questions/4577/does-gplv3-require-attribution

Also, github does not work for crediting authors if another person copies someone's code and inserts it.  The code will be shown under the copier's name.

**Comment by dbakewel** [comment]
Hmmm...I'm not sure that is correct. The license does not actually say that. It does allow something like that to be added but netbots has not done so, nor do I intend to. The license file, combined with git record (author and date) accomplish the same thing and seems to be the currently accepted practice. Keep in mind the license was created long before git existed. It is reasonable to assume that others will understand that this license applies to the netbots repository.

Regarding GitHub crediting authors, I know what your are getting at. We can talk about the merge conflicts with the last pull request. Git is great but it has limitations. To reduce these issues, most people use the following branching model: https://nvie.com/posts/a-successful-git-branching-model/ However that model requires use of a good desktop client since github does not support it. If you are going to work on other projects then spending some time learning a real git client and gitflow is worth your time.

**Comment by mcstoer** [comment]
From Wikpedia's Copyleft Article: https://en.wikipedia.org/wiki/Copyleft

> The source code files will usually contain a copy of the license terms and acknowledge the authors.

GPLv3 is a copyleft license and does require author attribution.

> The GNU General Public License is a free, copyleft license for software and other kinds of works.

See https://www.gnu.org/licenses/gpl-3.0.en.html

Read sections 4 and 5 for more detail.

The netbots repository seems fine other than those last merge conflicts.  Thanks for looking into them.
