### ISSUE TITLE
Is netbots code easy to understand?

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#76]
@lsh010815 , @MCSnapTurtle , @MCSnapTurtle , @JamesDarby345 , @jtaevans 

Hi everyone, since you have all looked at the netbots code now, I'd like you opinion. Is the netbots code easy to understand? 

What would make it easier for new people in the future? Should the code  be separated into more files? Should we use more python objects or are objects to confusing? More comments or better variable names? Better README? etc...

Any feedback is welcome. Thanks!

**Comment by mcstoer** [comment]
The most of the code is easy to understand.  When it isn't easy to understand, it's due to the usage of  more complex python.  Commenting is clear and the README seems adequate.

**Comment by MCSnapTurtle** [comment]
For the simple stuff, it is easy to read and comments are clear. 
Once it gets complex, I find it hard to read, however that may just be because I'm not familiar with python. Even the comments for the complex parts are sometimes harder to understand. My limited understanding might be a me problem, not a code problem.

Not sure if it is common practice for the README to contain information about the server code, but it would be helpful if the README explained the server, viewer and all the other behind the scenes code. This way, changing the server may become easier.

**Comment by dbakewel** [comment]
OK, I think what @MCSnapTurtle and @mcstoer are pointing out is that a separate architecture design document may be needed to explain how the complex parts of the server work. At least that's part of it. Some of the complex python may just be the need to know python.

**Comment by JamesDarby345** [comment]
Because AP students that have gone through ms wears curriculum know a lot about objects I don't think they would confuse students, it may confuse other people who haven't done these courses. Personally finding where the code is that does the thing I want to understand is the hardest part.
