### ISSUE TITLE
Is train to advanced to be a demo robot?

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#77]
@mcstoer suggested that the train.py demo robot moment is to advanced for a demo robot. Some players simply use train.py movement without much modification.

I would like to see a discussion in the comments. Should train.py be removed from demo robots and leave it up to players to figure movement out on their own? What kind of demo robot should replace train.py?

**Comment by MCSnapTurtle** [comment]
@mcstoer has a valid point. Compared to the other starting bots, train is the only moving bot that can avoid walls. The rest either ram into walls or don't move at all. Wall avoidance is something quite advanced. Yes, it is probably a good idea to remove train, because it's movement alone is superior to anything I have made (I have a wall avoiding, random direction moving bot).

You could replace train with a variant that does not turn when it is close to the wall. Instead, once it hits the wall, it changes direction. So basically, it moves like train, except it hugs the walls. So it still keeps track of where it is, and which wall it is beside, but only uses that information once it rams into a wall. This is definitely worse, but still keeps the "personality" of train, so I think it is a good replacement.

I could work on the "wall banging" train if the idea is fine.

**Comment by dbakewel** [comment]
I like the wall banging idea. @MCSnapTurtle I think you have enough to work on with https://github.com/dbakewel/netbots/issues/47. Let's wait for others feedback on this.

**Comment by MCSnapTurtle** [comment]
@dbakewel I would love to do the train changes before doing #47, because the train changes should be pretty quick to implement.

**Comment by MCSnapTurtle** [comment]
@mcstoer  and I have thought of a new demo bot. It find the closest enemy and moves in the opposite direction from it. I'll be working on this.

**Comment by JamesDarby345** [comment]
The train movement is rather good, it is what I have used for my bot but I just made it faster and turn sooner. It probably should be replaced or simplified.
