### ISSUE TITLE
Jamzone radius argument

### ISSUE THREAD

**Issue by mcstoer** [dbakewel/netbots#98]
**Is your feature request related to a problem? Please describe.**
There is no current way to vary jamzone sizes other than to change the server code.

**Describe the solution you'd like**
```
def mkJamZones(d, n):
    '''
    Randomly lay out jam zones. There are no rules about overlaps of anything else in arena.
    '''
    jamZones = []
    rad = d.conf['botRadius'] * 2

    for i in range(n):
        jamZones.append({
            'x': random.random() * d.conf['arenaSize'],
            'y': random.random() * d.conf['arenaSize'],
            'radius': rad
            })

    return jamZones
```

The line where the radius is set could be changed to
```
rad = d.conf['jamZoneRadius']
```
and a server argument could be added with the default of double the bot radius.

**Describe alternatives you've considered**
A multiplier of the bot radius could be used instead of set values.

**Comment by dbakewel** [comment]
Jam Zone size does vary based on botRadius, as you note above. This was done by design so that a robot would have to carefully park inside a zone only twice as big as the robot is. The Jamming effect only works if the robot is completely inside the Jam Zone.

```JamZoneRadius= d.conf['botRadius'] * 2```

I'd like to know how the current design works before we make any changes. I'm concerned that if a robot is designed to work with Jam Zones and then the size of the Zones start changing that it may add more complexity than makes sense for the robot to have to deal with. Also, 

Two other notes to consider to make Jam Zones fair:
1. Jam zones need to be small enough that if you can't find another robot by scanning that you can fire at Jam Zones and expect to hit something.
2. Jam zones should be big enough that parking inside one is not to difficult. So we need to consider speed and breaking.
